var  hi = "Hellow World";
console.log(hi);
console.log(typeof hi);
console.log('-----');
var number = 40;
console.log(number);
console.log(typeof number)
console.log('-----');
var boolean =  true;
console.log(boolean);
console.log(typeof boolean);
console.log('-----');
var vacio = null;
console.log(vacio);
console.log(typeof vacio);
console.log('-----');
var noDefinido;
console.log(noDefinido);
console.log(typeof noDefinido);
console.log('-----');
var simbolo = Symbol('something');
console.log(simbolo);
console.log(typeof Symbol);
//Variable global:
let vairableGlobal = "Soy una variable global";
// Variable scope
function variableScope(){
    //Variable scope
    num = 5;
}

